<?php

use App\Models\Unity;
use Illuminate\Database\Seeder;

class UnityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Unity::create([
            'razao_social' => 'Administrador Kando',
            'fantasy' => 'Administrador Kando',
            'email' => 'contato@kando-so.com.br',
            'cnpj' => '02.330.850/0001-83',
            'color' => '#FEC118',
            'nfe' => 'HOMOLOGACAO',
            'logo' => 'https://api.kando-so.com.br/storage/images/units/logo.png',
            'zipcode' => '84458-000',
            'street' => 'Rua América',
            'number' => '54',
            'district' => 'Centro',
            'country' => 1,
            'province' => 1,
            'city' => 69,
            'sunday' => false,
            'monday' => true,
            'tuesday' => true,
            'wednesday' => true,
            'thursday' => true,
            'friday' => true,
            'saturday' => false,
            'hour_sunday_in' => '11:00:00',
            'hour_sunday_interval_in' => '15:00:00',
            'hour_sunday_interval_out' => '16:30:00',
            'hour_sunday_out' => '21:00:00',
            'hour_monday_in' => '11:00:00',
            'hour_monday_interval_in' => '15:00:00',
            'hour_monday_interval_out' => '16:30:00',
            'hour_monday_out' => '21:00:00',
            'hour_tuesday_in' => '11:00:00',
            'hour_tuesday_interval_in' => '15:00:00',
            'hour_tuesday_interval_out' => '16:30:00',
            'hour_tuesday_out' => '21:00:00',
            'hour_wednesday_in' => '11:00:00',
            'hour_wednesday_interval_in' => '15:00:00',
            'hour_wednesday_interval_out' => '16:30:00',
            'hour_wednesday_out' => '21:00:00',
            'hour_thursday_in' => '11:00:00',
            'hour_thursday_interval_in' => '15:00:00',
            'hour_thursday_interval_out' => '16:30:00',
            'hour_thursday_out' => '21:00:00',
            'hour_friday_in' => '11:00:00',
            'hour_friday_interval_in' => '15:00:00',
            'hour_friday_interval_out' => '16:30:00',
            'hour_friday_out' => '21:00:00',
            'hour_saturday_in' => '11:00:00',
            'hour_saturday_interval_in' => '15:00:00',
            'hour_saturday_interval_out' => '16:30:00',
            'hour_saturday_out' => '21:00:00',
            'status' => 'ACTIVE'
        ]);
        Unity::create([
            'razao_social' => 'SoulPet Ltda',
            'fantasy' => 'SoulPet',
            'email' => 'contato@soulpet.com',
            'cnpj' => '14.640.465/0001-11',
            'color' => '#3880ff',
            'nfe' => 'HOMOLOGACAO',
            'logo' => 'https://api.kando-so.com.br/storage/images/units/logo.png',
            'zipcode' => '84458-000',
            'street' => 'Rua América',
            'number' => '54',
            'district' => 'Centro',
            'country' => 1,
            'province' => 1,
            'city' => 69,
            'sunday' => false,
            'monday' => true,
            'tuesday' => true,
            'wednesday' => true,
            'thursday' => true,
            'friday' => true,
            'saturday' => false,
            'hour_sunday_in' => '11:00:00',
            'hour_sunday_interval_in' => '15:00:00',
            'hour_sunday_interval_out' => '16:30:00',
            'hour_sunday_out' => '21:00:00',
            'hour_monday_in' => '11:00:00',
            'hour_monday_interval_in' => '15:00:00',
            'hour_monday_interval_out' => '16:30:00',
            'hour_monday_out' => '21:00:00',
            'hour_tuesday_in' => '11:00:00',
            'hour_tuesday_interval_in' => '15:00:00',
            'hour_tuesday_interval_out' => '16:30:00',
            'hour_tuesday_out' => '21:00:00',
            'hour_wednesday_in' => '11:00:00',
            'hour_wednesday_interval_in' => '15:00:00',
            'hour_wednesday_interval_out' => '16:30:00',
            'hour_wednesday_out' => '21:00:00',
            'hour_thursday_in' => '11:00:00',
            'hour_thursday_interval_in' => '15:00:00',
            'hour_thursday_interval_out' => '16:30:00',
            'hour_thursday_out' => '21:00:00',
            'hour_friday_in' => '11:00:00',
            'hour_friday_interval_in' => '15:00:00',
            'hour_friday_interval_out' => '16:30:00',
            'hour_friday_out' => '21:00:00',
            'hour_saturday_in' => '11:00:00',
            'hour_saturday_interval_in' => '15:00:00',
            'hour_saturday_interval_out' => '16:30:00',
            'hour_saturday_out' => '21:00:00',
            'status' => 'ACTIVE'
        ]);
    }
}
